
Beep: 
	gcc Beep.c -o Beep
	
princhar: 
	gcc princhar.c -o princhar

toobig: 
	gcc toobig.c -o toobig

base: base.c
	gcc base.c -o base
platinum: paltinum.c
	gcc print1.c -o print1

clean:
	del *.exe