
# 逗号运算符的使用


postage:
	gcc postage.c -o postage
	

cmpflt:
	gcc cmpflt.c -o cmpflt

while1:
	gcc while1.c -o while1

testscandf:
	gcc testscanf.c -o  testscanf

summming:
	gcc summing.c -o summing

clean:
	del *.exe